apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend
  namespace: argocd
  annotations: 
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/mlnawsdevops/backend-argocd.git
    targetRevision: main
    path: .
    helm:
      releaseName: backend
      valueFiles:
      - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: expense
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - PruneLast=true
